apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-sample
  namespace: test
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: test
  source:
    repoURL: https://github.com/tigerw2015/argocd-sample.git
    path: base
    targetRevision: HEAD
  sources: []
  project: default
